[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=45",
  "setuptools_scm>=6.2",
  "wheel",
]

[mypy]
ignore_missing_imports = true

[mypy-setup.py]

[tool.isort]
force_single_line = true
lines_after_imports = 2
profile = "black"

[tool.mypy]
disable_error_code = [
  "union-attr",
]
ignore_missing_imports = true
show_error_codes = true

[tool.setuptools_scm]
